---
title: "Problem Set 7: Elections 2018"
author: "Sofia Marie Mascia"
date: "18/11/2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(knitr)
library(lubridate)
library(haven)
library(dplyr)
library(kableExtra)
library(fs)
library(scales)
library(janitor)
```


```{r loading data, echo = FALSE}
election_data <- read_csv("election-context-2018.csv")
```


```{r}

california <- election_data %>%
  filter(state == "California") %>% 
  filter(county == "Los Angeles" | county == "San Francisco" | county == "San Benito" |county == "Marin" 
         |county == "Orange County" |county == "Madera" | county == "Riverside" | county == "San Luis Obispo"
         |county == "Ventura" | county == "San Diego"
         ) %>% 
  select(county, trump16, clinton16, romney12, obama12, demhouse16, rephouse16, white_pct, black_pct, hispanic_pct,   nonwhite_pct, foreignborn_pct, median_hh_inc, lesshs_pct, lesscollege_pct) %>% 
  mutate(low_education = lesshs_pct + lesscollege_pct)

#renaming the variables so they look nice in my app  
#   mutate(`Voted Trump 16` = as_factor(trump16),
#          `Voted Clinton 16` = as_factor(clinton16),
#          `Voted Obama 12` = as_factor(obama12),
#          `Voted Dem House 16` = as_factor(demhouse16),
#          `Voted Rep House 16` = as_factor(rephouse16),
#          `White Pop. Percent` = as_factor(white_pct), 
#          `Black Pop. Percent` = as_factor(black_pct),
#          `Hispanic Pop. Percent` = as_factor(hispanic_pct),
#          `Non-White Pop. Percent` = as_factor(nonwhite_pct),
#          `Foreign Born Pop. Percent` = as_factor(foreignborn_pct),
#          `Median House-hold Income` = as_factor(median_hh_inc),
#          `Less than Highschool Education` = as_factor(lesshs_pct), 
#          `Less than College Education` = as_factor(lesscollege_pct)
#         )
        
california %>% write_rds("ps_7.rds")
  

```

